import pandas as pd

df1 = pd.read_csv('./extract_atom.csv')
df2 = pd.read_csv('./e(n).csv')
df3 = pd.read_csv('./e(n+1).csv')
df4 = pd.read_csv('./e(n-1).csv')
df5 = pd.read_csv('./HOMO(N).csv')
df6 = pd.read_csv('./HOMO(N+1).csv')
df7 = pd.read_csv('./HOMO(N-1).csv')
df8 = pd.read_csv('./VIP.csv')
df9 = pd.read_csv('./VEA.csv')
df10 = pd.read_csv('./Mulliken_electronegativity.csv')
df11 = pd.read_csv('./Chemical_potential.csv')
df12 = pd.read_csv('./Hardness.csv')
df13 = pd.read_csv('./Softness.csv')
df14 = pd.read_csv('./Electrophilicity_index.csv')
df15 = pd.read_csv('./Nucleophilicity_index.csv')

df = pd.concat([df1, df2, df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15], axis=1, join='inner')
df.to_csv('./finnal_descri.csv', index=False)
